/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "on-tertiary-fixed": "#0d1c2d",
        "secondary-container": "#03c6b2",
        "on-tertiary-container": "#1c2b3c",
        "inverse-surface": "#e5e2e1",
        "on-surface": "#e5e2e1",
        "tertiary": "#b9c8de",
        "on-secondary-container": "#004d44",
        "surface-container-highest": "#353534",
        "surface-variant": "#353534",
        "primary": "#c4c0ff",
        "secondary": "#44e2cd",
        "background": "#131313",
        "error": "#ffb4ab",
        "surface-container-lowest": "#0e0e0e",
        "on-secondary-fixed": "#00201c",
        "on-primary": "#2000a4",
        "primary-fixed-dim": "#c4c0ff",
        "tertiary-fixed": "#d4e4fa",
        "surface-tint": "#c4c0ff",
        "tertiary-container": "#8392a6",
        "primary-container": "#8781ff",
        "tertiary-fixed-dim": "#b9c8de",
        "on-primary-fixed": "#100069",
        "on-tertiary-fixed-variant": "#39485a",
        "surface": "#131313",
        "on-background": "#e5e2e1",
        "outline-variant": "#464555",
        "error-container": "#93000a",
        "on-secondary": "#003731",
        "surface-container-low": "#1c1b1b",
        "surface-bright": "#3a3939",
        "inverse-on-surface": "#313030",
        "secondary-fixed-dim": "#3cddc7",
        "surface-dim": "#131313",
        "on-tertiary": "#233143",
        "on-surface-variant": "#c7c4d8",
        "secondary-fixed": "#62fae3",
        "inverse-primary": "#4f44e2",
        "on-secondary-fixed-variant": "#005047",
        "on-primary-container": "#1b0091",
        "surface-container": "#201f1f",
        "outline": "#918fa1",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#e3dfff",
        "surface-container-high": "#2a2a2a",
        "on-primary-fixed-variant": "#3622ca"
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      }
    },
  },
  plugins: [],
}
